### ISSUE TITLE
[FEAT] Style Component 적용

### ISSUE THREAD

**Issue by mina-gwak** [sally-ksh/sidedish#14]
## 💡 issue
[FEAT] Header, Card 컴포넌트를 Styled Component 방식으로 변경

## 📝 todo
- [x] app.scss를 글로벌 스타일로 변경
- [x] Header 컴포넌트에 Styled Component 적용
- [x] Card 컴포넌트에 Styled Component 적용
