### ISSUE TITLE
[FEAT] DB 설계 후 쿼리 테스트

### ISSUE THREAD

**Issue by sally-ksh** [sally-ksh/sidedish#16]
## 💡 issue
[FEAT] DB 설계 후 쿼리 테스트

## 📝 todo
- [ ] .welcome page 요청 - 기획전의 카테고리 id = 1의 메뉴 3가지의 목록 조회
- [ ] welcome page 요청 -  더보기 이전, 카테고리 default = "밑반찬" 의 메뉴 10개 목록 조회
- [ ]  "밑반찬" 의 메뉴의 전체 개수 조회
