### ISSUE TITLE
[FEAT] Exhibition 컴포넌트 마크업, 스타일링 구현

### ISSUE THREAD

**Issue by fivethreeeo** [sally-ksh/sidedish#17]
## 💡 issue
[FEAT] Exhibition 컴포넌트 생성
- 첫 화면 로드 시 목 데이터를 가져와 첫 번째 카테고리 렌더링
- 카테고리 클릭 이벤트 처리 x, 첫 화면 정적페이지만 완성하기

## 📝 todo
- [x] 타이틀, 카테고리, 아이템 마크업 & 스타일링
- [x] 첫 화면 로드 시 목데이터로 화면 구현
- [x] Exhibition의 첫 번째 카테고리 렌더링
