### ISSUE TITLE
[FEAT] DB 설계 수정, create, insert sql 작성

### ISSUE THREAD

**Issue by sally-ksh** [sally-ksh/sidedish#19]
## 💡 issue
[FEAT] DB 설계 수정, create, insert sql 작성

## 📝 todo
- [X] DB 설계 수정
  - [X]  기존 기획전과 이벤트 배지 부분, 할인 관련 수정
- [X] craete sql
- [X] insert 하면서 creat 수정
- [X] insert 문 작성 + 작은 테스트 케이스
