### ISSUE TITLE
[FEAT] Header 카테고리 메뉴 노출 기능 구현

### ISSUE THREAD

**Issue by fivethreeeo** [sally-ksh/sidedish#20]
## 💡 issue
[FEAT] Header 카테고리 메뉴 노출 기능 구현

## 📝 todo
- [x] 유저가 MenuList에 마우스를 올리면 레이어가 아래로 확장된다.
- [x] 마우스가 MenuList 영역을 벗어나면 확장됐던 내용이 사라지고 원래대로 돌아간다.
- [x] 헤더 보완 - 로고를 클릭하면 홈화면이 리로드 된다.
