### ISSUE TITLE
[FEAT] 기획전 기능 구현

### ISSUE THREAD

**Issue by sally-ksh** [sally-ksh/sidedish#27]
## 💡 issue
[FEAT] 기획전 내 카테고리별 추천메뉴 목록 기능

## 📝 todo
- [X] 당일 진행되는 기획전 조회
- [X] 진행되는 기획전에 해당하는 추천메뉴 목록 조회
- [X] Mock api 에 맞춰 기획전 메뉴 목록 반환
  - [X] 기획전 타이틀
  - [X] 기획전 내 추천메뉴 제목 목록
  - [X] 첫 화면 요청시 default 추천 메뉴  해당 메뉴 목록
  - [X] 메뉴 별 이미지 조회
  - [X] 메뉴 별 진행 중인 이벤트 조회
  - [X] 메뉴 별 진행 중인 이벤트에 대한 할인 정보 조회
  - [X] 메뉴 별 진행 중인 이벤트 있을 때 할인 가격 계산
- [ ] ~~기획전 내 사용자 추천 메뉴 요청에 대한 메뉴 목록~~ to Tany
