### ISSUE TITLE
[FEAT] 슬라이더 구현

### ISSUE THREAD

**Issue by mina-gwak** [sally-ksh/sidedish#28]
## 💡 issue
[FEAT] 슬라이더 구현
- 메뉴를 슬라이딩해서 보여주는 슬라이더 구현
- 재사용이 가능하도록 구현해보기

## 📝 todo
- [x] Category 컴포넌트에서 슬라이드 부분 분리
- [x] 마크업 수정
- [x] 슬라이딩 기능 구현
- [x] 목데이터를 사용해서 렌더링
