### ISSUE TITLE
[FEAT] 모달 구현

### ISSUE THREAD

**Issue by fivethreeeo** [sally-ksh/sidedish#35]
## 💡 issue
[FEAT] 모달 구현
- Portal을 이용해 모달 생성 구현
- 모달 내부 로직 구현
- 목데이터로 구현
- 하단 연관상품 슬라이더는 추후 추가 예정 (추가완료)

## 📝 todo
- [x] 컴포넌트 마크업, 스타일링
- [x] Protal을 사용해 모달 렌더링

<br>

- [x] 유저가 썸네일 이미지를 선택하면 메인 이미지가 변경된다.
- [x] 이미지 목록 중 유저가 선택한 이미지로 메인 이미지가 변경된다.
- [x] 메인 이미지로 보여지고 있는 이미지에는 테두리를 표시한다.

<br>

- [x] 주문 수량은 1 이상으로만 선택할 수 있다.
- [x] 주문 수량에 따라 상품금액, 배송비, 주문금액이 계산되어 표시된다.
- [x] 상품이 품절인 경우 ‘품절’ 버튼으로 나타낸다.
- [x] 할인이 있는 경우 할인 금액과 뱃지를 표시한다.
