### ISSUE TITLE
[FEAT] 배포하기

### ISSUE THREAD

**Issue by juni8453** [sally-ksh/sidedish#36]
## 💡 issue
수동 배포를 위한 작업 시작

## 📝 todo
- [x] develop-FE 브랜치 내부 작업물 clone -> npm run build 로 빌드
- [x] Aws Linux 서버 내부 nginx 설치
- [x] Spring boot 빌드 파일 및 React 빌드 파일 서버로 옮기기
- [x] 배포 테스트 중 ...
