### ISSUE TITLE
[FEAT] 주문하기 구현

### ISSUE THREAD

**Issue by sally-ksh** [sally-ksh/sidedish#46]
## 💡 issue
[FEAT] 메뉴 단일상품 주문 구현

## 📝 todo
- [X] 요청 api
- [X] 응답 api
- [X] 요청 데이터 검증 로직
- [X] 요청한 값에 대한 주문금액 등 검증 로직
- [X] 예외처리 or 메시지
- [X] 주문 가능 여부 확인
