### ISSUE TITLE
[FEAT] 추천 메뉴 클릭 시 조회 및 첫화면 더보기 클릭 시 추가 카테고리 조회 구현

### ISSUE THREAD

**Issue by juni8453** [sally-ksh/sidedish#49]
## 💡 issue
[추천 메뉴] 1 ~ 4 를 클릭했을 시 해당하는 메뉴를 3개 출력한다.
1. 풍성한 고기반찬
2. 편리한 반찬 세트
3. 맛있는 제철 요리
4. 우리 아이 영양 반찬 

[더보기] 버튼 클릭 시 나머지 카테고리 2개를 모두 출력한다.

## 📝 todo
- [x] 추천 메뉴 클릭 시 알맞은 메뉴 조회
- [x] 더보기 버튼 클릭 시 나머지 카테고리 2개 모두 조회
- [x] Controller 단에 @CrossOrigin 어노테이션 추가
- [ ] Menu Class Category.enum 의 koType 이름 좀 더 길게 맞춰주기
