### ISSUE TITLE
[FEAT] 기본적인 스프링 의존관계 설정 및 Spring Data Jdbc 연동

### ISSUE THREAD

**Issue by juni8453** [sally-ksh/sidedish#8]
## 💡 issue
Controller, Service, Repository 의존 관계 주입 및 Spring Data Jdbc 를 연동하기 위한 작업을 실시

## 📝 todo
- [x] Controller, Service, Repository 클래스 생성 및 의존 주입
- [x] Spring Data Jdbc 사용을 위해 연동 테스트
- [x] MySQL 연동 후 schemas.sql, data.sql 파일 작성
- [x] develop-BE 브랜치에 Push
